## Copyright © 2020, Oracle and/or its affiliates.
## All rights reserved. The Universal Permissive License (UPL), Version 1.0 as shown at http://oss.oracle.com/licenses/upl

title: "Deploy Dify and Oracle Autonomous Database (ADB) Select AI Sidecar on Oracle Cloud Infrastructure (OCI)"
stackDescription: "Set up the open-source LLM platform Dify alongside Oracle Autonomous Database (ADB) Select AI Sidecar on Oracle Cloud Infrastructure (OCI). This stack enables natural language to SQL, federated queries, and AI-powered data applications with seamless integration."
schemaVersion: 1.1.0
version: "20220422"
locale: "en"

variableGroups:
  - title: Hidden
    visible: false
    variables:
      - instance_boot_volume_size
      - instance_boot_volume_vpus
      - instance_flex_shape_memory
      - instance_flex_shape_ocpus
      - db_system_credentials_password_details_password_type
      - db_system_db_version
      - db_system_instance_count
      - db_system_instance_memory_size_in_gbs
      - db_system_instance_ocpu_count
      - db_system_shape
      - db_system_storage_details_is_regionally_durable
      - db_system_storage_details_system_type
      - instance_image_source_id

  - title: Required Configuration
    visible: true
    variables:
      - region
      - compartment_ocid
      - availability_domain
      - adb_name
      - license_model
      - enable_mysql      
      - mysql_display_name
      - enable_postgresql
      - db_system_display_name
      - db_password
      - instance_display_name
      - vcn_ai_vcn_id
      - subnet_private_id
      - subnet_public_id
      - instance_shape
      - ssh_authorized_keys
      - bucket_region
      - bucket_name
      - oci_access_key
      - oci_secret_key
      - dify_branch

variables:
  region:
    title: Region
    type: oci:identity:region:name
    required: true
    visible: false

  compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    visible: true
    title: "Create in compartment"

  availability_domain:
    type: oci:identity:availabilitydomain:name
    required: true
    visible: true
    title: "Availability domain"
    dependsOn:
      region: ${region}
      compartmentId: ${compartment_ocid}

  adb_name:
    type: string
    required: true
    visible: true
    title: "ADB Name"

  license_model:
    type: enum
    required: true
    visible: true
    title: "Choose ADB license"
    enum:
      - "BRING_YOUR_OWN_LICENSE"
      - "LICENSE_INCLUDED"
    default: "LICENSE_INCLUDED"

  mysql_display_name:
    type: string
    required: true
    visible: ${enable_mysql}
    title: "MySQL Database Display Name"
    description: "Display name for MySQL database system (also used as hostname label)"
    default: "mysql4adbaisidecar"

  enable_mysql:
    type: boolean
    required: true
    visible: true
    title: "Enable MySQL Database"
    description: "Enable MySQL database installation and configuration"
    default: true

  enable_postgresql:
    type: boolean
    required: true
    visible: true
    title: "Enable PostgreSQL Database"
    description: "Enable PostgreSQL database installation and configuration"
    default: true

  db_system_display_name:
    type: string
    required: true
    visible: ${enable_postgresql}
    title: "PostgreSQL Database Display Name"
    description: "Display name for PostgreSQL database system"
    default: "postgresql4adbaisidecar"

  db_password:
    type: password
    required: true
    visible: true
    title: "Database password"
    description: "Set the password for your Database ADMIN user here."
    # renders a second field to re-enter the password for confirmation
    confirmation: true
    pattern: "^(?!.*admin)(?=.*[0-9])(?=.*[a-z])(?=.*[A-Z])(?!.*[\"]).{12,30}$"

  instance_display_name:
    type: string
    required: true
    visible: true
    title: "Compute instance name"

  vcn_ai_vcn_id:
    type: oci:core:vcn:id
    required: true
    visible: true
    title: "VCN"
    description: "Select existing virtual cloud network"
    dependsOn:
      compartmentId: ${compartment_ocid}

  subnet_private_id:
    type: oci:core:subnet:id
    required: true
    visible: true
    title: "Private Subnet"
    description: "Select existing private subnet for database"
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${vcn_ai_vcn_id}

  subnet_public_id:
    type: oci:core:subnet:id
    required: true
    visible: true
    title: "Public Subnet"
    description: "Select existing public subnet for compute instance"
    dependsOn:
      compartmentId: ${compartment_ocid}
      vcnId: ${vcn_ai_vcn_id}

  ssh_authorized_keys:
    type: oci:core:ssh:publickey
    title: "Add SSH keys"
    description: "Upload a public key that you already have."
    required: true
    visible: true

  bucket_region:
    type: enum
    required: true
    visible: true
    title: "Region for Object Storage"
    description: "Select the region where Object Storage bucket will be created"
    enum:
      - "ap-osaka-1"
      - "ap-tokyo-1"
      - "us-ashburn-1"
    default: "ap-osaka-1"

  bucket_name:
    type: string
    required: true
    visible: true
    title: "Object Storage Bucket Name"
    description: "Name of the bucket to be created for Dify"

  oci_access_key:
    type: string
    required: true
    visible: true
    title: "OCI Access Key"
    description: "OCI Object Storage Access Key for S3 compatibility"

  oci_secret_key:
    type: string
    required: true
    visible: true
    title: "OCI Secret Key"
    description: "OCI Object Storage Secret Key for S3 compatibility"

  bucket_namespace:
    type: string
    required: false
    visible: false
    title: "Object Storage Namespace"
    description: "Your OCI tenancy's object storage namespace (will be automatically detected if left blank)"

  instance_image_source_id:
    type: enum
    required: true
    visible: true
    title: "Choose the image according to your region."
    enum:
      - "ocid1.image.oc1.ap-tokyo-1.aaaaaaaauig5vniqgg6ithp3t2iixkdbekipdyndz5dtzepno6g4uwn2cg2q"
      - "ocid1.image.oc1.ap-osaka-1.aaaaaaaakubn2okgusevio3dcanojxysaeod42dkey2tilbr7bfvkiconb6q"
      - "ocid1.image.oc1.us-chicago-1.aaaaaaaafrdmn335msygwxikywohkaxxscjicyf5cmhcnthqfnxwk3tlmuua"
    default: "ocid1.image.oc1.ap-osaka-1.aaaaaaaakubn2okgusevio3dcanojxysaeod42dkey2tilbr7bfvkiconb6q"

  instance_shape:
    type: enum
    required: true
    visible: true
    title: "Choose the shape for compute instance."
    enum:
      - "VM.Standard.E4.Flex"
      - "VM.Standard.E5.Flex"
    default: "VM.Standard.E5.Flex"

  instance_boot_volume_size:
    visible: false
  instance_boot_volume_vpus:
    visible: false
  instance_flex_shape_memory:
    visible: false
  instance_flex_shape_ocpus:
    visible: false

  dify_branch:
    type: string
    required: true
    visible: true
    title: "Dify Branch/Tag"
    description: "Branch or tag name to use when cloning the Dify repository"
    default: "1.8.1"

  db_system_credentials_password_details_password_type:
    type: string
    required: true
    visible: false
    title: "PostgreSQL Password Type"
    description: "Password type for PostgreSQL database"
    default: "PLAIN_TEXT"

  db_system_db_version:
    type: number
    required: true
    visible: false
    title: "PostgreSQL Database Version"
    description: "Version of PostgreSQL database"
    default: 16

  db_system_instance_count:
    type: number
    required: true
    visible: false
    title: "PostgreSQL Instance Count"
    description: "Number of PostgreSQL instances"
    default: 1

  db_system_instance_memory_size_in_gbs:
    type: number
    required: true
    visible: false
    title: "PostgreSQL Instance Memory Size (GB)"
    description: "Memory size in GB for PostgreSQL instances"
    default: 16

  db_system_instance_ocpu_count:
    type: number
    required: true
    visible: false
    title: "PostgreSQL Instance OCPU Count"
    description: "OCPU count for PostgreSQL instances"
    default: 2

  db_system_shape:
    type: string
    required: true
    visible: false
    title: "PostgreSQL Database Shape"
    description: "Shape for PostgreSQL database system"
    default: "PostgreSQL.VM.Standard.E5.Flex"

  db_system_storage_details_is_regionally_durable:
    type: boolean
    required: true
    visible: false
    title: "PostgreSQL Regional Durability"
    description: "Whether PostgreSQL storage is regionally durable"
    default: true

  db_system_storage_details_system_type:
    type: string
    required: true
    visible: false
    title: "PostgreSQL Storage System Type"
    description: "Storage system type for PostgreSQL"
    default: "OCI_OPTIMIZED_STORAGE"

outputs:
  bucket_region:
    title: "Object Storage Bucket Region (Selected Region)"
    displayText: "Object Storage Bucket Region (Selected Region)"
    type: copyableString
    visible: true
  bucket_name:
    title: "Object Storage Bucket Name"
    displayText: "Object Storage Bucket Name"
    type: copyableString
    visible: true
    value: ${oci_objectstorage_bucket.dify_bucket.name}
  bucket_namespace:
    title: "Object Storage Bucket Namespace"
    displayText: "Object Storage Bucket Namespace"
    type: copyableString
    visible: true
  admin_username:
    title: "Database Administrator Username"
    displayText: "Database Administrator Username"
    type: copyableString
    visible: true
  adb_connection_string:
    title: "Autonomous Data Warehouse High Connection String"
    displayText: "Autonomous Data Warehouse High Connection String"
    type: copyableString
    visible: true
  adb_connection_string_full:
    title: "Full Oracle Connection Descriptor (HIGH with MUTUAL TLS)"
    displayText: "Full Oracle Connection Descriptor (HIGH with MUTUAL TLS)"
    type: copyableString
    visible: true
  adb_connection_string_for_dify:
    title: "ADB Connection String for Dify"
    displayText: "ADB Connection String for Dify"
    type: copyableString
    visible: true
  mysql_internal_fqdn:
    title: "MySQL Internal FQDN"
    displayText: "MySQL Internal FQDN"
    type: copyableString
    visible: true
  mysql_internal_connection_string_for_dify:
    title: "MySQL Internal Connection String for Dify"
    displayText: "MySQL Internal Connection String for Dify"
    type: copyableString
    visible: true
  postgresql_primary_endpoint_fqdn:
    title: "PostgreSQL Primary Endpoint FQDN"
    displayText: "PostgreSQL Primary Endpoint FQDN"
    type: copyableString
    visible: true
  postgresql_internal_connection_string_for_dify:
    title: "PostgreSQL Internal Connection String for Dify"
    displayText: "PostgreSQL Internal Connection String for Dify"
    type: copyableString
    visible: true    
  ssh_to_instance:
    title: "Convenient command to ssh to the instance"
    displayText: "Convenient command to ssh to the instance"
    type: copyableString
    visible: true    
  dify_url:
    title: "Dify URL"
    displayText: "Dify URL"
    type: copyableString
    visible: true
  langfuse_url:
    title: "Langfuse URL"
    displayText: "Langfuse URL for LLM observability"
    type: copyableString
    visible: true
